apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nginx-deployment
  labels:
    app: app-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-nginx
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      containers:
        - name: app-nginx
          image: stacksimplify/kube-nginxapp1:1.0.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-nginx-nodeport-service
  labels:
    app: app-nginx
spec:
  type: NodePort
  selector:
    app: app-nginx
  ports:
    - port: 80
      targetPort: 80
